### ISSUE TITLE
Integrate the editors also in the creating dialog

### ISSUE THREAD

**Issue by jonnitto** [neos/neos-ui#1034]
At the moment, not all available editors (e.g. DateTime) are available in the creationDialog. In order to make advanced use of https://github.com/Flowpack/Flowpack.NodeTemplates/, it is important to have all of them in the dialog.

**Comment by jonnitto** [comment]
In the properties definition, you need to set the editor inside of the inspector, in the creatinDialog not. The editor are available. The editorOptions aren't working, but this is another issue…

**Comment by dimaip** [comment]
Hmm actually I'm sure some advanced editors like Image editor won't work, so re-opening.

**Comment by dimaip** [comment]
Or does image editor work for you?

**Comment by jonnitto** [comment]
I‘ll test it

**Comment by jonnitto** [comment]
Yes, you are right. The image editor doesn't work correctly.

**Comment by bwaidelich** [comment]
I can confirm, that the `ImageEditor` won't work from the `creationDialog`: The `MediaBrowser` won't be shown – this is probably a challenge to achieve UX wise..

**Comment by bweinzierl** [comment]
I stumbled across this problem today while using the mentioned Flowpack.NodeTemplates. In my case the ImageEditor and the AssetEditor both cannot open the MediaBrowser. This would be a much needed Feature to greatly improve the backend user experience.

**Comment by bwaidelich** [comment]
Since we're planning to integrate the "creation dialog properties" feature into Neos 5.1 (see https://discuss.neos.io/t/rfc-allow-node-properties-to-appear-in-the-creation-dialog/3687) this issue will get more relevance. Maybe we can come up with an intermediate solution like a custom editor with limited browsing functionality?

**Comment by bwaidelich** [comment]
FYI: Currently those are the core editors that don't (completely) work in Creation Dialogs due to the secondary view:
* `Neos.Neos/Inspector/Editors/ImageEditor`
* `Neos.Neos/Inspector/Editors/AssetEditor`
* `Neos.Neos/Inspector/Editors/RichTextEditor`
* `Neos.Neos/Inspector/Editors/CodeEditor`

We briefly discussed this in our weekly team meeting yesterday. One (probably simpler but not so UX-y way) might be to open the original modal _on top_ of the Creation Dialog modal.
Alternatively we could maybe expand the secondary view like we currently do with DateTime properties:

![image](https://user-images.githubusercontent.com/307571/69796798-ef109d00-11ce-11ea-8428-c58cfab9ecf4.png)

![image](https://user-images.githubusercontent.com/307571/69796814-f33cba80-11ce-11ea-999b-f51986ca8f8c.png)

I have no clue how much work that would be.. For now I'll disable those editors for https://github.com/neos/neos-development-collection/issues/2173

**Comment by Sebobo** [comment]
This is also an interesting topic for the new media ui. 
Maybe embedding the secondary inspector is the best option.
I anyway wanted to make the media selector fully responsive.

**Comment by bwaidelich** [comment]
With #2870 merged this can be closed, right?
