### ISSUE TITLE
Spinner icon is rotating together with its square background...

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#1187]
![peek 2017-10-25 16-03](https://user-images.githubusercontent.com/837032/32000113-41c531c2-b99e-11e7-9356-35c4bab90f43.gif)

**Comment by petmat** [comment]
I'll take a look at this!

**Comment by mstruebing** [comment]
Hey @petmat, do you still plan to work on this?

**Comment by petmat** [comment]
Hi, I would very much still like to look at this, but I've had some serious issues installing and running Neos CMS. I'm not sure if it is because I'm trying to run it on Windows. But just now it seemed that I got the Neos CMS installed so I can progress to getting Neos UI up and running. So if it is still ok with you I would like to see if I can fix this.

**Comment by markusguenther** [comment]
I will take a look if it is Ok @petmat

**Comment by petmat** [comment]
Yeah of course @markusguenther , sorry it took me so long!
