### ISSUE TITLE
Create a stable E2E testing stack with possibly selene and retractor

### ISSUE THREAD

**Issue by Inkdpixels** [neos/neos-ui#149]
In an effort to stabilize the E2E stack, and align it to the unit tests. Using selene is way more stable, since it does not implement a custom DSL to selenium as webdriberIO does currently, thus, it is less error prone. 

Using retrator is way more expressive, since we won't need any hard coded HTML ID's to find elments, instead we would just import the JS source file into the test spec and retractor will handle the search for the component based on it's React internal name and the given optional props. The result will be way more expressive, clean and less confusing in case a element with the given ID cannot be found.

@dimaip @grebaldi @skurfuerst @GerDner @ryzy 

https://github.com/LiquidLabsGmbH/selene
https://github.com/LiquidLabsGmbH/retractor

**Comment by dimaip** [comment]
I'm not deep into the subject, but what you are describing looks totally sane to me.

**Comment by Inkdpixels** [comment]
Currently paused due to a bug in the Firefox WebDriver - https://www.bountysource.com/issues/34273142-firefox-47-unable-to-connect-to-host-127-0-0-1-on-port-7055-after-45000-ms

**Comment by Inkdpixels** [comment]
FYI: I will remove the current E2E stack for now, our priority should really be on unit tests for now, and we should pick up the E2E topic later on I guess.

**Comment by Inkdpixels** [comment]
I paused the work on this, since I believe that we should focus on getting a solid unit test coverage first. Afterwards we should re-visit this

**Comment by skurfuerst** [comment]
Closing currently, agreed with Inkdpixels :)

**Comment by dimaip** [comment]
Can we tag issues for 1.0 instead of just closing all the rest?
IMO integrational tests are very important to get done properly ASAP, even if that happens post-1.0.
Though to tell you frankly I have no idea how we are going to reach the level of stability needed for 1.0 without those tests in place.

As for what @Inkdpixels said about unit tests coverage, we have that for core functionality like reducers and some sagas, but I don't see it working really well for the UI part, so I definitely would not wait for the perfect unit test coverage before reintroducing the e2e tests.
If nobody takes on it, I will try to get back to it some time soon.

**Comment by skurfuerst** [comment]
If you want to work on it, feel free to re-open. I personally will rather use unit tests first...
