### ISSUE TITLE
Disabled/Timed DocumentNodes are not marked correct in the nodetree

### ISSUE THREAD

**Issue by johannessteu** [neos/neos-ui#1500]
If a document node is disabled it is marked as hidden right now. In the old ui there was a `x`-icon.

Old:
![bildschirmfoto 2017-12-27 um 15 25 22](https://user-images.githubusercontent.com/769789/34384094-3a7ed19a-eb1a-11e7-808c-87668968a87d.png)

New:
![bildschirmfoto 2017-12-27 um 15 25 42](https://user-images.githubusercontent.com/769789/34384099-3f97b3f4-eb1a-11e7-89e2-e3d4daccc8a2.png)

**Comment by johannessteu** [comment]
Right now there is no solution to stack fontawesome icons. The Icon-Component could be improved to support the stack feature FA provides. We could also set stacked icons "cornored" like this
https://codepen.io/anon/pen/aEprwy

**Comment by lorenzulrich** [comment]
Would we do that in `Packages/Application/Neos.Neos.Ui/packages/react-ui-components/src/Icon` using a new property `stackedIconClassName`?

**Comment by lorenzulrich** [comment]
And should `cornered` be an option or do we assume we always want the stacked item to be cornered?

**Comment by lorenzulrich** [comment]
(Asking because that could be a task for a beginner such as me ;-))

**Comment by dfeyer** [comment]
> And should cornered be an option or do we assume we always want the stacked item to be cornered?

No option, I think it's more consistent to have it on the same corner, like in the old UI

> Would we do that in Packages/Application/Neos.Neos.Ui/packages/react-ui-components/src/Icon using a new property stackedIconClassName?

Yes I think this feature can live in Icon component

**Comment by johannessteu** [comment]
We had earlier a discussion about this in Slack and how to implent. The outcame was to introduce a new StackedIconComponent with some props to configure it. I think i already worked on it, but never pushed it. Can look tomorrow if i can find that change if someone wants to have a look at it

**Comment by johannessteu** [comment]
https://github.com/johannessteu/neos-ui/tree/stacked-icons

**Comment by lorenzulrich** [comment]
Ah, very good! Will you take care of implementing also do rest or should I use your work as a start?

**Comment by johannessteu** [comment]
You can use it as a start!

**Comment by lorenzulrich** [comment]
Hidden should be doable, but timed nodes will be harder because the API doesn't provide this value yet. 

API of the old UI:

![image](https://user-images.githubusercontent.com/1816023/35594299-ef5b8190-0612-11e8-977e-8f89dda2beb7.png)

API of the new UI:

![image](https://user-images.githubusercontent.com/1816023/35594359-266dff28-0613-11e8-9ce5-a6f5aec55d7c.png)

**Comment by lorenzulrich** [comment]
Furthermore, the implementation on the old UI is very specific to these use-cases, see the CSS:

```
&.neos-hidden {
	span + span:after {
		@include fa-icon();
		content: $fa-var-times-circle;
		position: absolute;
		left: 12px;
		top: 0px;
		font-size: 12px;
		color: $warning;
		background: #fff;
		height: 8px;
		width: 8px;
		margin-top: 11px;
		line-height: 9px;
		@include border-radius(10px);
	}
}

&.neos-timedVisibility {
	span + span:after {
		@include fa-icon();
		content: $fa-var-clock-o;
		position: absolute;
		left: 12px;
		top: 0px;
		font-size: 12px;
		color: $blue;
		background: #fff;
		height: 8px;
		width: 10px;
		margin-top: 11px;
		line-height: 9px;
		@include border-radius(10px);
	}
}
```

They have been designed to look good (using different bg/foreground colors and border-radius).

I'm not sure what the best way to go is:

* If we do it in an abstract way as @johannessteu suggests, we need quite some properties for the `<StackedIcon>` component: height, width, color, background-color, border-radius. IMO this "perverts" the idea of having an abstraction because we only do this for two use-cases (hidden and timed).

Wouldn't it be better to take the way the old UI did by just injecting a class name and defining some custom CSS for these two cases so we have the exact result as before - which looked quite good?

Any thoughts here?

**Comment by dimaip** [comment]
> Hidden should be doable, but timed nodes will be harder because the API doesn't provide this value yet.
Feel free to add it to the API.

> Wouldn't it be better to take the way the old UI did by just injecting a class name and defining some custom CSS for these two cases so we have the exact result as before - which looked quite good?
I'd be fine with that. Go for whatever works, we could always abstract it away and refactor.

Thanks for getting into this stuff!

**Comment by johannessteu** [comment]
As nothing really happend here, i'll take care. Is that ok for you @lorenzulrich ?

**Comment by lorenzulrich** [comment]
Thanks for taking care, @johannessteu. I started doing this some months ago but got stack with my insufficient React knowledge. Looks great now!
