### ISSUE TITLE
"Open in target dimension" does always open a new browser tab

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-ui#1749]
The button "Open in target dimension" behaves differently in the new UI.
![image](https://user-images.githubusercontent.com/883552/38424457-69b98564-39b1-11e8-822f-b4e6428da822.png)

### Steps to Reproduce

1. Hit the "open in target dimension" button while in backend
2. A new browser tab should have opened showing the frontend
3. Go back to the backend-tab (dont close the frontend-tab)
4. Hit the "open in target dimension" button again

#### Expected behavior
The frontend-tab should have been reloaded

#### Actual behavior
A new frontend-tab has opened

### Affected Versions

Neos: 2.2.9

UI: 1.0.9 (also master-branch), 

It is working as expected when I switch to old UI.

**Comment by dimaip** [comment]
An interesting issue. If I remove `rel="noopener noreferrer"` from the link, it starts working as expected.
I propose to do just that.
I don't think that would be a security issue, since those links open the same site on the same domain anyways, and the guest frame has many more ways to access the host anyways.
Any objections? @grebaldi @kitsunet @mstruebing  and all?

**Comment by grebaldi** [comment]
What about `window.opener.opener`? Could be an issue with user generated content...

**Comment by dimaip** [comment]
@grebaldi good point, true. Then I have no idea how to fix this issue.
