### ISSUE TITLE
Integrate visual regression testing

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#190]
One last thing left before we can really start working rapidly with refactoring styles is visual regression testing.
I'm currently deciding between two tools:
- https://github.com/garris/BackstopJS -- works via CasperJS, more cheesy, easier to integrate
- https://github.com/gemini-testing/gemini -- works in real browsers via selenium, crazily advanced, powers Yandex and made by them
- https://github.com/BBC-News/wraith

I'm inclined to try BackstopJS first, just to not waste time, unless you change my mind :-)

What's your opinion, do we need to test our components for visual regressions in different real browsers or should we just go with a simpler tool for now?

**Comment by RafaelKa** [comment]
👍 for Gemini + saucelabs

**Comment by dimaip** [comment]
@RafaelKa perhaps you would like to give this a try?

**Comment by RafaelKa** [comment]
@dimaip yes this is interesting topic for me, also i'll do that shortly...

But there is some other Points, that must be done before Beta-Phase:

- Split repository like its done for flow|neos-development-collection, because the size of this repo scares me just now, and after applying Gemini + saucelabs tests it will scale the repo to the colossal sizes, which are not needed on Production(or Site developers) machines at all.

**Comment by dimaip** [comment]
@RafaelKa great!
We have split our codebase into smaller packages, but they will stay in one repository, like most JS projects do. It shouldn't hinder testing it in any way I believe.

**Comment by RafaelKa** [comment]
A little Task list:

**for Neos team member only!:** 

- [ ] Create Open Source account for Neos on SauceLabs + Sub Account for neos-ui
- [ ] Setup JWT Addon for Sauce-Connect for Travis -> [Because of: "Note that due to security restrictions, the Sauce Labs addon is not available on pull request builds unless you use the JWT Addon."](https://docs.travis-ci.com/user/sauce-connect/) <- describes ho to do that as well
- [ ] 

For everyone:
- [ ] write few gemini or simple selenium tests to run some smoke tests during setup with sauce + gemini
- [ ] check if current travis env contains all required PHP stuff for running Neos instance, because we are on `language: node_js` env. If PHP is not available use one of following: 
  - [ ] install it with apt-get directly in sh script to prevent slowing up other jobs of buld
  - [ ] docker image especially for serving Neos job. See -> [Using Docker in Travis](https://docs.travis-ci.com/user/docker/#Using-a-Docker-Image-from-a-Repository-in-a-Build)
- [ ] write sh script for build, setting up and running Neos instance of current commit
- [ ] Setup connection to Sauce-Cloud (PR Ready!)
- [ ] draw up docs how to use it

feel free to add some steps

**Comment by RafaelKa** [comment]
Small udate for creating Sauce-Labs Account! 
It seems to be repository bounded. 
Please go to https://saucelabs.com/beta/signup/OSS/None as logged out user.

**Comment by skurfuerst** [comment]
closing this one, as we probably won't tackle it for 1.0.0 musit have
