### ISSUE TITLE
Is nodetype select dialog has scrolling, the help message is hidden below under scroll

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#2086]
![image](https://user-images.githubusercontent.com/837032/44404561-d17e6d80-a55f-11e8-9cfd-a2b38ca18b2a.png)

**Comment by h1Modeling** [comment]
I can look into this (maybe this weekend). Just to clarify: What is the actual expected behavior? I expect the help message should be sticky at the bottom of the panel. Is this correct? Similar to the below image?

<img width="906" alt="bildschirmfoto 2018-08-23 um 20 48 51" src="https://user-images.githubusercontent.com/17990673/44545782-4abfc100-a716-11e8-86fe-3032021a728a.png">

**Comment by dimaip** [comment]
@h1Modeling yep, that would be one way to do it.
In the old UI it was floating in the tooltip, but I never liked how it worked.
