### ISSUE TITLE
Copying nodes acorss dimenions and websites

### ISSUE THREAD

**Issue by davidspiola** [neos/neos-ui#2127]
### Description

This feature is about improving multi dimension and website support within the UI. It would be quite helpful for editors to have the same/similar tooling the have right now for a multi site environment as well. 

Since both websites share the same root path `sites` it would be great to use the existing implementation and extend it in a way, that you can past into other websites and dimensions. I had a short discussion with Christian Müller about it and he said, that is should work out from the CR perspective. 

Important to know is that the coping target **does't** have to be necessarily within the some dimension, and probably only coping of nodes does make sense IMHO.

**Comment by dimaip** [comment]
Hey, so I had a quick look into the issue.
First of all, it is possible to copy nodes across dimensions on master. It's been implemented recently.
Now comes the problem of copying nodes across sites. It is easy to set current clipboard path in local storage, the way we do with other persisted settings... But the problem is that local storage is scoped to the current domain only, so you can't share it between sites.

Let's discuss possible solutions:

1. Persist some part of this state in user session data on PHP side. Would complicate things a little, but should be doable.
2. Use some hacky cross-domain cookie or local storage solution. Please let's not.
3. Any better ideas? Maybe @aertmann or @kitsunet have ideas?

**Comment by dimaip** [comment]
I tried to do it the first way, see the PR
