### ISSUE TITLE
The data picker saves date time of browser timezone but not the timezone of php configuration

### ISSUE THREAD

**Issue by sunweiye** [neos/neos-ui#2147]
### Description
If the browser timezone is different from the timezone of php, wenn a date and time is selected with date picker in the backend, the date and time is not the selected value. The value with time difference is saved in database.

### Steps to Reproduce
Background: 
- There is a filed names `startTime` using date picker in the page configuration.
- The browser client uses timezone `Central European Summer Time (UTC+2)` .
- The Timezone in PHP is `UTC`

1. Select a date time (2018-10-01 00:00:00) with date picker in the backend
![backend-date-picker](https://user-images.githubusercontent.com/18660206/46201895-9f59eb80-c315-11e8-8fdb-3074bf7148a9.jpg)
2. Load the DateTime with `q(node).property('startTime')` In fusion (or php) 
3. The date time is shown in the timezone of UTC but not the value that is set
![fusion-date](https://user-images.githubusercontent.com/18660206/46202112-33c44e00-c316-11e8-8e77-bdcf75fb0778.jpg)

#### Expected behavior

The date time should be save with the same value that is selected in the date picker.

#### Actual behavior

Neos simply saves the value from browser without timezone checking

[What actually happened]

### Affected Versions

Neos:

UI: Latest

**Comment by hlubek** [comment]
We also just hit that bug in a site we updated to the new Neos UI. I'd say we didnt' have this bug with the old interface.

I'd expect a property of type `DateTime` with format `format: 'd-m-Y'` to be stored as UTC with value `2018-10-16 00:00:00.000000`.

There's also a notable difference between choosing "Today" and clicking one of the days in the picker: the button "Today" submits the current time instead of "00:00:00" (with the same timezone difference).

**Comment by dimaip** [comment]
I can confirm this bug as well!

**Comment by hlubek** [comment]
I still wonder what should be the expected value here:

We have to distinguish between a date selector (ignoring the actual time) and a date time selection - both are use cases that are useful:

**Date selector**

PHP / Neos only allows to store `DateTime` (including a timezone and time information), so what should be the expected time / timezone value when storing only a particular date?

Idea: store the value as `2018-10-17T00:00:00.000000+0:00`, thus we ignore a local timezone completely, since it doesn't matter for selecting only a particular _date without time_.

**Date time selector**

The current timezone of the browser (or a configurable timezone - in Neos or the User) should be used when submitting / storing the date time instance. The stored value has to keep the timezone _offset_ information e.g. when using Neos in a global use case with multiple editors in different timezones.

It might depend on the property whether a fixed timezone (for all editors) or the actual browser / user timezone should be used.

Note: A timezone should be configured using  a _location_ (e.g. `Europe/Berlin`) and not as an offset, since in countries with daylight savings there are different timezone offsets for dates during a year.
