### ISSUE TITLE
Pressing escape key doesn't close modals/dialogs

### ISSUE THREAD

**Issue by aertmann** [neos/neos-ui#2168]
### Description

When pressing the escape key when viewing a modal/dialog it doesn't close as would be expected.

### Steps to Reproduce

1. Open insert element modal or confirm deletion dialog

#### Expected behavior

That the modal/dialog clsoes

#### Actual behavior

Nothing happens

### Affected Versions

UI: 1.3

**Comment by mstruebing** [comment]
Good point, I think the `dialog` is already enhanced with `closeOnEscape` but it seems there are some missing points :)

**Comment by JamesAlias** [comment]
The `Dialog` component renders a `Portal`. 
It is rendered _"visually above"_ and _"DOM-wise beside"_ the `appContainer` which still keeps the `focus`.
Once you klick anywhere, the rendered Portal, including it's backdrop is focused. Pressing the ESC key then actually closes the Dialog as expected. Which is weird, because the EventListener for the ESC trigger is attached to `document`.

There are multiple possible fixes for this.
As I am currently working on the migration of the Dialog component to TypeScript I will pick up this Issue and try to fix it by updating `react-portal` to _latest_ (4.x) which already comes with "close on escape" and "click outside" included.

**Comment by JamesAlias** [comment]
I guess the problem is, that the `eventListeners` for the ESC key are added to the parent `document` of the `Portal` but the `focus` is still in the content canvas' `iframe`, thus in a _different_ document.

When we open the same dialog with the "add node"-Button in the content tree (in the left side panel) the ESC trigger works as expected.

I fixed it by auto focusing dialog, wich also switches the focus to the top level document.
Not beautiful, but effective.
If you see a better fix, let us know or open a PR 👍
