### ISSUE TITLE
Failed "out of band rendering" breaks UI

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-ui#2489]
### Description

When the out-of-band-rendering of a Node returns an empty string, the content iFrame is reloaded with an error:
```
!!! Content Element (rendered out-of-band) with context path "/sites/some/context-path" not found in returned HTML from server (which you see below) - Reloading the full page!
```

Afterwards new elements can't be added before the whole browser is refreshed manually.

### Steps to Reproduce

To trigger the behavior you can tweak `ReloadContentOutOfBand::renderContent()` to return an empty string.
Afterwards create a new element

(alternatively follow the steps described by @kdambekalns in https://github.com/neos/neos-ui/issues/2365#issuecomment-473870306)

#### Expected behavior

The element is inserted, the iFrame is reloaded and new elements can be added hitting the "+"-buttons

#### Actual behavior

The element is inserted, the iFrame is reloaded but hitting the "+"-buttons has no effect.

#### Note

Looking at the redux state the `@neos/neos-ui/UI/SelectNodeTypeModal/CANCEL` action is dispatched immediately after the `@neos/neos-ui/UI/SelectNodeTypeModal/OPEN` action

### Affected Versions

UI: 2.0+

**Comment by kdambekalns** [comment]
Also see my second comment (https://github.com/neos/neos-ui/issues/2365#issuecomment-473873622) for some more on the Redux state…

**Comment by markusguenther** [comment]
After quite some time of investigation we found a way to prevent the issue. Sadly not in an optimal way.

**What happend**

When you create a new node that has an empty renderedContent in RenderContentOutOfBand response, the UI throw an error and reloads the GuestFrame.

This behavior is intended but lead to the error that it was not possible to use the NodeToolBar after that reload on each node without reloading the whole window or changing the preview mode.

**Problem**

We found out that we have an issue with the reload of the guestframe when it is triggered from inside the guest frame. The events are all fired, but not in the right order.

So we want to handle the "click outside handling" when you click on the "add Node" Button to close dropdowns like the publishing. But now we have the issue that the that the saga for the nodeCreationWorkflow is fired to early and we close the dialog we just opened with the "click outside handling" of the "add node" button.

We did not find a proper way to change the event order, yet. At the moment we add a data-attribute to detect that we triggered the "click outside handling"  from the NodeToolBar inside the GuestFrame and skip the event.

So it can happen that you have a opened publish drop down and it does not close when you open the node creation dialog. But when you select the node type in the dialog the drop down will close. And in general the drop down is opened before you click the "add node" button. Because you need to click on the node to get the NodeToolBar and then the dialog will close.

**Comment by markusguenther** [comment]
Forget to thank @skurfuerst for the debug help. 🙏
