### ISSUE TITLE
Preview button leads to validation error for hidden pages

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-ui#2500]
### Description

When opening the preview for a hidden page a validation error shows up instead of handling the error or showing the preview.

### Steps to Reproduce

1. Hide page in backend
2. Click on preview button

#### Expected behavior

Either a meaningful message or the actual preview.

If it shouldn't be possible to see the preview for hidden pages, the editor shouldn't get the option to open it. 
If it should be possible, then we need to show the rendered page.

#### Actual behavior

The following error appears: 

```Validation failed while trying to call Neos\Neos\Ui\Controller\BackendController->redirectToAction()```

### Affected Versions

Neos: 4.3

UI: 3.4

**Comment by Sebobo** [comment]
Older versions of the UI might be affected too, but didn't have time yet to check.

**Comment by kdambekalns** [comment]
The same holds true for "hidden before/after" and it worked with the legacy UI, according to a customer.

**Comment by kdambekalns** [comment]
So it seems quite some people are triping over this and the "ugly URLs" as well as hidden things being shown unexpectedly.

Maybe a solution would be to add the parameter only when previewing a document that is itself hidden. That would avoid the problem, but keep the behaviour for other documents?!

**Comment by dimaip** [comment]
I would expect such feature to work this way: hidden status on the document node would be ignored, but all other nodes within it would respect their hidden status.

**Comment by dlubitz** [comment]
@kdambekalns At the moment this featue leads to some (hopefully unexpected) bahavior. If I have an hidden content node and click the preview button, I see the hidden content in the preview. (see screenshots). AFAIS the feature should just show hidden document nodes, but not content nodes.

(Neos UI 4.0.1, Neos 4.3.7)

![image](https://user-images.githubusercontent.com/13046100/69666947-650ceb00-108d-11ea-8f03-5db850ff8152.png)

![image](https://user-images.githubusercontent.com/13046100/69666962-6f2ee980-108d-11ea-81a8-409af1b68e6c.png)

**Comment by kdambekalns** [comment]
Ok, I'll give that a go…

**Comment by bwaidelich** [comment]
@kdambekalns This is affected by https://github.com/neos/neos-development-collection/issues/2653 as well (which we plan to include into 5.1). Would be great if we could join forces here!

**Comment by kdambekalns** [comment]
To fix this for Neos 4.0 onwards, I am working on this now. But when trying, the request that renders the preview does not even have `Neos.Neos:Backend.GeneralAccess` so I get just "Sorry, the page you requested was not found.". How can this fail for anyone in any other way? I am puzzled on so many levels now…

**Comment by kdambekalns** [comment]
Ok, this started out as a bugfix for the validation error. That must be fixed, and it is by now.

But I got carried away by the wish to actually preview a hidden node (which also works by now), but had the side effect of also showing all hidden content in the preview.

Too late did I realize that… this worked before the React UI only because we have very specialized handling for showing URLs that have `@some-workspace` parts in them. With the way this is handled now, one can only have _one node with one content_ being shown. And that means either you do not get the node, or it will "contain" all hidden nodes as well. There is o middle ground.

That being said, one customer requirement was "editors need the URL for pages not yet published or still hidden", e.g. to include them in a newsletter. And that is still possible, even if we revert the "show hidden documents" part - the URL can be copied from the browser just fine, it will start to work as soon as the document is no longer hidden.

After all, as @robertlemke pointed out to me today: The correct preview of a hidden document is a 404.

**Comment by kdambekalns** [comment]
The validation error is fixed, preview work "as expected" (see above).
