### ISSUE TITLE
Insert mode is reset after opening group on create new modal

### ISSUE THREAD

**Issue by jakob-LIS** [neos/neos-ui#2573]
### Description

The insert mode is reset to a default whenever a group is opened or closed. The problem is best explained with the attached GIF.

### Steps to Reproduce

1. Create new NodeType on a Node that serves as a ContentCollection.
2. Change insert mode to `insert into`
3. Open a group 
4. Insert mode was reset to `insert after`

#### Expected behavior

The insert mode should not change when opening and closing groups on the same modal.

#### Actual behavior

 See GIF below
![Oct-23-2019 13-37-54](https://user-images.githubusercontent.com/48725233/67389177-5d43bd80-f59a-11e9-918b-cb2fc569ec7b.gif)

### Affected Versions

Neos: 4.x

UI: 3.8.x and 4.0.x

**Comment by lisjagu** [comment]
If I understood correctly, when `onPanelToggle` of `ToggablePanel` happens, `NodeTypeGroupPanel` triggers store action `actions.UI.AddNodeModal.toggleGroup` which causes the `SelectNodeType` modal to receive updated props and to recalculate `insertMode` with a different result than before so the modal is rerendered. 

A workaround seems to be to completely remove the behavior of `componentWillReceiveProps` from the `SelectNodeType` modal which leads to the desired behavior in this context.

However, I don't know the reason this behavior was added in the first place and don't know if it might cause other problems I can't see right now. 

The actual bug seems to be that the received props `allowedSiblingNodeTypes` and/or `allowedChildNodeTypes` have changed in a situation they shouldn't have.

**Comment by dimaip** [comment]
Hi @lisjagu!
Thanks a lot for looking into it!

> However, I don't know the reason this behavior was added in the first place and don't know if it might cause other problems I can't see right now.

The logic is this: we need to be able to calculate the default state for the insertion mode, taking 3 things into account: `allowedSiblingNodeTypes`,  `allowedChildNodeTypes` and `preferredMode`.
All of these change dynamically based on whichever node you focus in the tree.

> The actual bug seems to be that the received props allowedSiblingNodeTypes and/or allowedChildNodeTypes have changed in a situation they shouldn't have

I think we are comparing two objects by reference there which are not referentially equal (they are cloned somewhere it seems), so it basically issues setState on each render.
We could surely use a deep object comparison there to fix the bug, but I'd just rather rework the whole thing somehow (sorry, it's late and I don't have any good ideas now).

**Comment by klfman** [comment]
I also experience this issue with neos-ui 4.0.4 and neos 4.3.11
