### ISSUE TITLE
Wrong icon for hotel

### ISSUE THREAD

**Issue by jan-vodila** [neos/neos-ui#2697]
### Description

Hotel icon is mapped to bed instead of hotel.

### Steps to Reproduce

1. Create Document node type and as an icon set `icon: 'hotel'`

#### Expected behavior

Hotel icon should be shown: https://fontawesome.com/icons/hotel?style=solid

#### Actual behavior

Bed icon is shown: https://fontawesome.com/icons/bed?style=solid

In the [/packages/react-ui-components/src/Icon/mapper.ts](https://github.com/neos/neos-ui/blob/master/packages/react-ui-components/src/Icon/mapper.ts#L148) hotel is mapped to `'hotel': 'fas fa-bed'`, but it should be `'hotel': 'fas fa-hotel'`

[What actually happened]

### Affected Versions

Neos: v5.1.6

UI version: v5.1.4

**Comment by jonnitto** [comment]
I had just this morning the same issue… As @markusguenther worked on the integration of the new version of FontAwesome I was so free to assign him to this issue. As I know, he is offline today, but I'm sure he will respond quickly

**Comment by markusguenther** [comment]
Hi thanks for the report. The mapper for compatibility reasons I  guess. Because the old UI had other names. So I guess that is just for backward compatibility.

The mapper has not changed for a while, but you can use all Icons of FA of course with the own classes.
But we should adjust that and use FA own types here. End of the year the last version (3.3) is end of life and then the old UI is dead.

So we probably put that on the agenda for 5.3.
I personally think it would also no big deal to change the icon. But would be better to have one of the elders with more knowledge about that involved. @dimaip @kitsunet
