### ISSUE TITLE
Warning of the inline validation message needs z-index

### ISSUE THREAD

**Issue by akappler** [neos/neos-ui#2712]
### Description

If some text is below an invalid inline element, e.g. headline, the texte below is above the validation error message

#### Expected behavior

Is above the element

UI: 5.1

**Comment by markusguenther** [comment]
Thanks for reporting that Issue @akappler 🙇 
Could you please provide a screenshot. Thanks in advance.

**Comment by markusguenther** [comment]
This has been solved:

'''The neosBackendContainer has been removed with the old emberjs content module. Because this container could not be found the container has been added to the beginning of the body tag.

Now we adjust the position to the end of the body section.

Thanks to @bwaidelich and @suffle for this hint 💙 

Fixes: #2828 https://github.com/neos/neos-ui/pull/2847'''
