### ISSUE TITLE
A restricted editor is able to click on publish to live and gets raw exceptions back

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#2796]
### Description

![restrictedEditor](https://user-images.githubusercontent.com/642226/95765426-263a5080-0cb2-11eb-818a-1d3672731bc4.gif)

### Steps to Reproduce

1. Log with an user with the RestrictedEditor role
2. Change something
3. Hit the publish to live button

#### Expected behavior

Publish to live is not enabled even when changes are made

Better: The editor cannot change content when own workspace is targeted to live

#### Actual behavior
See above

### Affected Versions

Neos: 5.3

UI: 5.3

You can get this information by running `composer show` or using the package management module within Neos.
The UI version can also be found inside the left sidebar after version 1.0.3.

**Comment by bweinzierl** [comment]
In addition to that the editor is able to select "live workspace" in the target workspace dropdown. This should not be an option.

**Comment by lorenzulrich** [comment]
I agree. The question is if the user should be allowed to see the LIVE workspace, but only in preview modes. So they could see LIVE, but not edit it and not try to publish to it. What do you think?

**Comment by markusguenther** [comment]
Hello,

I make my first research and in general, the UI has already a mechanism to prevent that.
But actually, it seems that we have a bug when something is changed.

Workspaces can be readonly, and we check if the workspace is readonly and if we are able to publish globally or just locally. That works on the initial state. When we edit something, the information is not correct anymore. I have created a little video.


https://user-images.githubusercontent.com/1014126/145684527-b0d3406f-852e-4a2c-96c1-bceed7adbbb8.mp4

So I need now to find the error, where we loose the correct data. If not it is maybe a way to prevent editing as the workspace is readonly. From the name readonly I would also expect that no creating and editing is possible. But not sure if this is still a bug because we change the behavior to the current state.

**Comment by mhsdesign** [comment]
is this solved @markusguenther? https://github.com/neos/neos-ui/pull/2994
