### ISSUE TITLE
Handle longer property labels / positioning of the help icon

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-ui#2976]
### Description

If a label gets longer, it is cut off. The help sign is the misplaced right next to the checkbox

![image](https://user-images.githubusercontent.com/642226/140095708-eafa036f-ee39-4826-9a1d-200aad1e07d7.png)

Neos: 7.1
UI: 7.1

**Comment by markusguenther** [comment]
Nice catch... it seems to be broken also in Neos 5.3, but it is not that hard because the icon is just a bit cut off.
But guess we should also target Neos 5.3.
<img width="759" alt="Screenshot 2021-11-08 at 15 27 30" src="https://user-images.githubusercontent.com/1014126/140759827-42325517-419d-4c07-a136-c98873483161.png">

**Comment by markusguenther** [comment]
Will be released with version 5.3.12
