### ISSUE TITLE
!!! TASK: Remove plugin views

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-ui#3534]
WIP

we need to adjust the ui first before we can merge https://github.com/neos/neos-development-collection/pull/4330 

following things need to be purged:

- MasterPluginEditor
- PluginViewEditor
- PluginViewsEditor
- plugin view endpoints (in javascript + fusion integration)

@grebaldi since you, as far as i remembered, tested the plugin views lately, maybe you have more insight and can help me with the cleanup?

**Comment by grebaldi** [comment]
> since you, as far as i remembered, tested the plugin views lately, maybe you have more insight and can help me with the cleanup?

Well :sweat_smile:, I did not test them, actually, because I didn't know how. This is why I raised the question of whether this concept is even needed at all :D

That being said, I'll help you of course, If I can :) As for the plan you've outlined so far, I believe that the editors can be safely removed (just for the fact that they are meaningless without an underlying plugin concept).

That last point though:
> plugin view endpoints (in javascript + fusion integration)

...I'd be surprised if the UI has any such plugin-specifics in its Backend API (might very well be true though - I'd just be surprised :D).

**Comment by bwaidelich** [comment]
> we need to adjust the ui first before we can merge https://github.com/neos/neos-development-collection/pull/4330

https://github.com/neos/neos-development-collection/pull/4330 has been merged already (quite a while ago). Is there anything left to do?

**Comment by mhsdesign** [comment]
yes we didnt cleanup the ui so far at all ^^
