### ISSUE TITLE
Editables with tagName other than `div` (e.g. span) cause an infinite loop in CKeditor

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#668]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

CKeditor doesn't like to work on editables with some tag types, e.g. `span` or `h1`. In those cases it just hangs the browser tab.

As a quick fix I propose to replace all tags by `div` on the UI side, when initializing the CKeditor.

**Steps to reproduce:**
create and editable with tagName `span`, go to that page and observe your browser to hang up.

**Comment by dimaip** [comment]
To ease debugging, the ckeditor gets stuck in an infinite loop here: https://github.com/ckeditor/ckeditor-dev/blob/305b2bb688cd6fbda0d88b6c966b24e639937ed2/core/htmlparser/fragment.js#L107

**Comment by mlewand** [comment]
We definitely didn't intend to create editor on inline elements. The reason for this is that native [conenteditable on inline](http://codepen.io/mlewand/pen/RGGxOj) will behave differently across the browsers - while it's handled fine in Firefox and Chrome, it will be implicitly converted into an inline-block element. This causes it to display it differently, thus it was a no-go for us.

Then again using editor in inline element, will require you to use ENTER_BR mode, which is discouraged.

Are you sure that the editor hangs there? I did a quick testing on my end (major branch/upcoming 4.7.0 release) and it works fine, here's screencast: [inline-editor-recording.zip](https://github.com/neos/neos-ui/files/902140/inline-editor-recording.zip). I'm also adding a screen as my soft somehow messed up recording resolution ![screen](https://i.imgur.com/PQejxYL.png) 😿

Anyway, I'd think about rethinking the structure so that CKE can be created in block elements. We won't officailly support editor in inline elements like span, strong anytime soon - and even though you might have some success on tinkering around, you could get to major troubles later in terms of browser interaction.

**Comment by dimaip** [comment]
Hey @mlewand, thanks a lot for looking into it. I'm not too deep into CKeditor integration, I just see that when I change tagName from `div` to `span` or `h1`, it hangs (`section` works though). If I try to debug it, it gets into an infinite loop at the place that I mentioned.
It's kind of hard to debug though, as we are currently including minified build of CKeditor, and I don't know really how it's supposed to be updated. A npm package could really help here...

@skurfuerst, maybe you could take a deeper look into why it happens, as you know this part better? Maybe we need to update CKeditor version or smth?

**Comment by skurfuerst** [comment]
I'll check that :)

**Comment by mlewand** [comment]
@dimaip you can find source CKEditor version at https://www.npmjs.com/package/ckeditor-dev 🙂 I agree that working on minified version is not the beste experience ever 😄

**Comment by dimaip** [comment]
@mlewand nice! @skurfuerst promised to take care of the issue, so that may be useful to him.

**Comment by dimaip** [comment]
This seems to have been fixed with the latest refactoring.
