### ISSUE TITLE
Content-Metadata Scripts break CSS :nth-child selectors in userland code

### ISSUE THREAD

**Issue by grebaldi** [neos/neos-ui#737]
As reported by https://neos-project.slack.com/team/benjamink in slack:

The new UI renders some inline skript-tag inside the backend, which make some css styles incorrect when using the `:nth-child()` selector.

In Slack: https://neos-project.slack.com/archives/C0U0KEGDQ/p1495552368521373

**Comment by hlubek** [comment]
With the approach of having a script tag to store metadata this cannot be prevented as far as I know. Having a single script tag somewhere "outside" for metadata does not work in respect to caching of individual content segments.

So one idea would be to use the HTML Augmenter to add the metadata as an attribute in `\Neos\Neos\Ui\Aspects\AugmentationAspect::contentElementAugmentation`, so no additional DOM element would be created. This only has the drawback of a slower initial load time since the metadata has to be extracted, JSON decoded from attributes of DOM elements. In doubt we should probably go the safe way (least surprise for integrators) and have a benchmark if it's actually such a big issue.

**Comment by dimaip** [comment]
I don't see how we can possibly fix it with the current approach.
