### ISSUE TITLE
Tooltips for buttons

### ISSUE THREAD

**Issue by mstruebing** [neos/neos-ui#802]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

The old UI have tooltips for buttons (i.e. add 'Create new' for the button to create new content elements) and we are currently having none.

**Comment by akoenig** [comment]
Good idea! I worked with this out-of-the-box component before and it worked pretty good. We could create a wrapper component in our own `react-ui-components` package for shielding our internal implementation. What do you think?

**Comment by dimaip** [comment]
@akoenig makes sense.

Also there's a WIP PR trying to tackle this issue: https://github.com/neos/neos-ui/pull/818
Don't know if @janinadanger has plans to finish it.

**Comment by johannessteu** [comment]
I'll ask her on monday and overtake if needed @dimaip

**Comment by dimaip** [comment]
Oh please do, I was so reluctant to mess with this change :joy:

**Comment by johannessteu** [comment]
Spoke to @janinadanger - will overtake and try to refactor it

**Comment by dimaip** [comment]
I think we could release 1.0 without this if no one is up for finishing it for the release.
@dfeyer suggest to use native tooltips instead of custom ones for the sake of performance and having less glitches. I tend to agree with him.
Thoughts?

**Comment by johannessteu** [comment]
Actually i think this is a must have for 1.0 as it is important to (new) user do explain and declare things. For instance Inspector tabs etc. We also use it for validation result rendering. And i'm not sure if native tooltips dies work for the validation result rendering. But we would need a solution for that anyway. I mean the Feature *is* finished. Since quite a time. We just need someone to push the merge button. If we keep this longer open it has to rebased again and again. It is already rebased like 3 times. @Inkdpixels also reworked it on the vienna sprint to match latest coding guidelines and was happy with merging it. So it just needs more or less a final rebase and merge.

**Comment by dimaip** [comment]
@johannessteu validation is a different case. I think for everything else we could use native tooltips.
Anyways, I'll rebase and merge as is for now, then somebody (@dfeyer?) could maybe switch to native tooltips in some places.

**Comment by dimaip** [comment]
Native tooltips are merged. I'll add another issue for improved tooltips for validation.
