### ISSUE TITLE
After CKE mangles content the inline NodeToolbar becomes wrongly positioned

### ISSUE THREAD

**Issue by dimaip** [neos/neos-ui#905]
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

CKE changes content like `<p></p>` into `<p><br></p>`. E.g. this: https://github.com/neos/Neos.Demo/blob/master/Resources/Private/Content/Sites.xml#L796

This makes all nodes on the page to change height, after CKE has been initialised.
This causes inline NodeToolbar to be incorrectly positioned, _after the page has been reloaded from the inspector_.

![image](https://user-images.githubusercontent.com/837032/30157038-e2077140-93c9-11e7-8262-c04841c98ec7.png)

**Comment by dimaip** [comment]
@skurfuerst do we want this for 1.0? Got ideas how to fix it?
This should either be fixed in CKE (don't insert those <br>'s) or we would need an event when all inline editors has been initialised, so we could re-position the toolbar.
IMO this one is pretty minor, if not easy to fix I'd postpone it and just fix content in the demo site.

**Comment by grebaldi** [comment]
I'd say this is actually not a bug. Those "bogus br's" are actually needed to prevent the p tag from collapsing to 0px height and thus making it possible to place the cursor in it. 

Actually it's a bug, that aloha doesn't do the same - so this should definitely be fixed in the Demo package.

However, it might be still sensible to reposition the inline toolbar after an inline editor of the focused node has been initialized.

**Comment by grebaldi** [comment]
Hmm...  I can't reproduce this any longer.

Can you confirm, @dimaip?

**Comment by dimaip** [comment]
Indeed I can not!
